"""
Django settings for footwear_erp project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path
import environ
from datetime import timedelta

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 👈 2. Initialize environ
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)
# 👈 3. Tell environ exactly where your .env file is located
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

env_allowed_hosts = os.environ.get('ALLOWED_HOSTS', '.localhost,localhost,127.0.0.1')
ALLOWED_HOSTS = env_allowed_hosts.split(',')


# Application definition

SHARED_APPS = (
    'django_tenants',  # Must be first
    'customers',       # Your Client and Domain models

    # 🌟 CORE AUTHENTICATION (For Public Master Admin)
    "accounts",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party apps
    "rest_framework",
    "django_filters",
    "rest_framework_simplejwt",
    "corsheaders",
)

TENANT_APPS = (
    # 🌟 CORE AUTHENTICATION (For Isolated Store Admins)
    "accounts",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",

    # Business Logic Apps
    "products",
    "inventory",
    "sales",
    "purchasing",
)

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django_tenants.middleware.main.TenantMainMiddleware', # 🌟 Add this at the absolute top
    'django.middleware.security.SecurityMiddleware',

    # Serves Django admin CSS/JS files in production.
    "whitenoise.middleware.WhiteNoiseMiddleware",

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 1. Routes traffic for storea.localhost, storeb.localhost, etc.
ROOT_URLCONF = 'footwear_erp.urls_tenant'

# Public-schema routing is configured near the django-tenants settings below.

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.debug',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'footwear_erp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": os.environ.get("DB_NAME"),
#         "USER": os.environ.get("DB_USER"),
#         "PASSWORD": os.environ.get("DB_PASSWORD"),
#         "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
#         "PORT": os.environ.get("DB_PORT", "5432"),
#     }
# }

# Replace the DATABASES section of your settings.py with this
# tmpPostgres = urlparse(os.getenv("DATABASE_URL"))

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': tmpPostgres.path.replace('/', ''),
#         'USER': tmpPostgres.username,
#         'PASSWORD': tmpPostgres.password,
#         'HOST': tmpPostgres.hostname,
#         'PORT': 5432,
#         'OPTIONS': dict(parse_qsl(tmpPostgres.query)),
#         # Important for Neon scale-to-zero behaviour
#         "CONN_MAX_AGE": 0,
#         "DISABLE_SERVER_SIDE_CURSORS": True,
#     }
# }


DATABASES = {
    "default": env.db("DATABASE_URL"),
}

# OVERRIDE the default postgres engine with the tenant engine
DATABASES['default']['ENGINE'] = 'django_tenants.postgresql_backend'

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

# Neon can scale to zero, so avoid keeping stale persistent connections.
DATABASES["default"]["CONN_MAX_AGE"] = env.int("DB_CONN_MAX_AGE", default=0)
DATABASES["default"]["DISABLE_SERVER_SIDE_CURSORS"] = True



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Yangon'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

AUTH_USER_MODEL = "accounts.User"

SIMPLE_JWT = {
    # Change from minutes=5 to hours=12 (Covers a full warehouse shift)
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12), 
    
    # Keep the refresh token long so they don't have to log in every single morning
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# DEFAULT_FROM_EMAIL = 'noreply@footwearinventory.com'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Your real email credentials
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default="") 
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default="")
DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL",
    default="Chue Family Admin <info.chuefamily@gmail.com>",
)

# Allow credentials (cookies, auth headers) cross-origin
CORS_ALLOW_CREDENTIALS = True

# Use Regex to dynamically allow ANY tenant subdomain on your local Vite port.
# This prevents you from needing a massive list of every store URL.
PROD_CORS_REGEX = env("PROD_CORS_REGEX", default=r"a^")

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://.*\.localhost:5173$",  # Matches storea.localhost:5173, storeb.localhost:5173
    r"^http://localhost:5173$",      # Matches base localhost
    r"^http://127\.0\.0\.1:5173$",   # Matches local IP
    PROD_CORS_REGEX,  
]

PROD_CSRF_DOMAIN = env("PROD_CSRF_DOMAIN", default="https://chuefamily.online")

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://*.localhost:5173",       # Trusts all tenant subdomains making POST requests
    PROD_CSRF_DOMAIN,
]


# HTTPS / reverse proxy settings
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

TENANT_MODEL = "customers.Client"  # app_name.ModelName
TENANT_DOMAIN_MODEL = "customers.Domain"

# Use the public URL configuration when the request host belongs to the public schema.
PUBLIC_SCHEMA_URLCONF = "footwear_erp.urls_public"
