# Generated by Django 4.2.30 on 2026-07-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='on_trial',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_plan',
            field=models.CharField(default='TRIAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
