# Generated by Django 4.2.30 on 2026-07-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_on_trial_client_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='is_active',
            new_name='on_trial',
        ),
        migrations.RemoveField(
            model_name='client',
            name='subscription_plan',
        ),
    ]
