# Generated by Django 4.2.30 on 2026-07-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_customer_updated_at_order_total_revenue_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_revenue',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale')], db_index=True, default='RETAIL', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at', 'order_type'], name='sales_order_created_fb91c0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='sales_order_status_2602a7_idx'),
        ),
    ]
