# Generated by Django 4.2.30 on 2026-07-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_order_options_remove_order_total_revenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cost_at_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
