# Generated by Django 4.2.30 on 2026-07-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productvariant_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Supplier purchase cost per unit, used for profit reporting.', max_digits=10),
        ),
    ]
